'use client';

import { useEffect, useState } from 'react';
import Navbar, { type NavLink } from '@/components/Navbar';
import SiteFooter from '@/components/SiteFooter';
import ContactSection from '@/components/ContactSection';
import DirectusVisualEditing, { directusAttr, isDirectusVisualEditingFrame } from '@/components/DirectusVisualEditing';
import { elementText, pageElement, type PageElement } from '@/lib/page-elements';
import { ArrowRight, BadgeCheck, Camera, Check, Clapperboard, GraduationCap, Headphones, MonitorPlay, Mic2, Radio, Settings2, Sparkles, Tv, Video, WandSparkles } from 'lucide-react';

type Locale = 'es' | 'en';
type Field = 'text' | 'secondary_text' | 'tertiary_text' | 'image';
const LOCALE_KEY = 'dsolution-language';

const navLinks = {
  es: [['Inicio', '/'], ['Servicios', '/servicios'], ['Portafolio', '/#portafolio'], ['Proceso', '/#proceso'], ['Contacto', '#contacto']] as NavLink[],
  en: [['Home', '/'], ['Services', '/servicios'], ['Portfolio', '/#portafolio'], ['Process', '/#proceso'], ['Contact', '#contacto']] as NavLink[],
};

const copy = {
  es: {
    cta: 'Planificar mi evento', heroEyebrow: 'Soluciones audiovisuales', heroTitle: 'Eventos, streaming y producción en vivo', heroText: 'Planificamos, configuramos y operamos sistemas audiovisuales para eventos presenciales, transmisiones multicámara, podcasts y equipos que necesitan trabajar con calidad profesional.', heroSecondary: 'Ver capacidades',
    trust: [['Producción profesional', 'De la preproducción a la entrega final'], ['Eventos presenciales', 'Barcelona y proyectos en España'], ['Transmisión estable', 'Full HD como base y 4K bajo requerimiento'], ['Equipo técnico', 'Cámaras, audio, luces, switcher e intercom']],
    servicesEyebrow: 'Nuestros servicios', servicesTitle: 'Soluciones audiovisuales completas', servicesText: 'Nos enfocamos principalmente en eventos y streaming profesional, con capacidades adicionales para podcast, instalación, postproducción y capacitación técnica.',
    services: [['Streaming profesional', 'Transmitimos eventos multicámara a YouTube, Facebook, TikTok, Instagram, Zoom, Teams o web propia, con gráficos, audio de consola y grabación simultánea.'], ['Dirección de TV y shows en vivo', 'Diseñamos la preproducción, guion técnico, escaleta, tiros de cámara, coordinación de operadores y dirección en vivo desde switcher e intercom.'], ['Producción de podcast', 'Creamos setups de video podcast con cámaras, audio por canales separados, iluminación, gráficos, intro/outro y clips para redes.'], ['Instalación audiovisual', 'Instalaciones temporales o fijas para salas, empresas, colegios, iglesias y espacios que necesitan cámaras, sonido, luces o streaming.'], ['Postproducción de video', 'Edición básica, intermedia o avanzada, multicámara, reels, subtítulos, limpieza de audio, color básico y gráficos.'], ['Capacitación técnica', 'Formamos equipos internos para operar cámaras, audio, iluminación, streaming y flujos básicos de producción.']],
    streamingEyebrow: 'Servicio destacado', streamingTitle: 'Transmitimos tu evento a donde esté tu audiencia', streamingText: 'Creamos transmisiones estables, profesionales y bien planificadas para eventos presenciales, conferencias, marcas, iglesias, agencias y creadores.', streamingCta: 'Planificar mi streaming',
    streamingBullets: ['Multiplataforma: YouTube, Facebook, TikTok, Instagram y web propia', 'Zoom, Teams y eventos cerrados', 'Producción multicámara con gráficos y lower thirds', 'Audio profesional desde consola', 'Grabación simultánea limpia y con gráficos', 'Subtítulos automáticos con IA bajo requerimiento', 'Base Full HD 1080p y 4K bajo cotización'],
    trainingEyebrow: 'Capacitación técnica', trainingTitle: 'Formamos a tu equipo para producir con confianza', trainingText: 'Capacitamos a equipos de empresas, colegios, universidades, iglesias e instituciones para que puedan operar sus propios sistemas audiovisuales con más seguridad.',
    trainingBullets: ['Cámaras DSLR, mirrorless, estudio, PTZ y configuración', 'Audio profesional y consolas digitales', 'Iluminación, DMX, Avolites o GrandMA según proyecto', 'Streaming y realización en vivo', 'Flujos de trabajo antes, durante y después del evento', 'Capacitación de 1 a 3 días según necesidad'],
    toolsEyebrow: 'Tecnología y software', toolsTitle: 'Herramientas que dominamos', toolsText: 'Trabajamos con herramientas profesionales para producir, transmitir, grabar, editar y entregar contenido audiovisual de calidad.', equipmentTitle: 'Equipo profesional',
    processEyebrow: 'Nuestro proceso', processTitle: 'Así trabajamos en tu proyecto',
    process: [['Análisis y reunión', 'Conocemos el evento, objetivos, duración, formato y requerimientos técnicos.'], ['Diseño y propuesta', 'Creamos la propuesta técnica, equipos, roles, guion técnico y plan de producción.'], ['Montaje y pruebas', 'Instalamos cámaras, audio, luces, red, switcher y realizamos pruebas antes del directo.'], ['Producción en vivo', 'Operamos y dirigimos el evento con comunicación, control técnico y máxima estabilidad.'], ['Entrega final', 'Entregamos streaming, grabación limpia, versión con gráficos o material editado.']],
    projectsEyebrow: 'Trabajos realizados', projectsTitle: 'Espacios para tus fotos reales', projectsText: 'Aquí podrás subir imágenes reales de eventos, streaming, podcast, instalaciones y backstage técnico desde Directus.',
    projects: [['Evento corporativo', 'Transmisión multicámara'], ['Conferencia', 'Streaming y operación técnica'], ['Podcast profesional', 'Set, cámaras, audio e iluminación'], ['Instalación audiovisual', 'Sistema preparado para operar'], ['Show en vivo', 'Dirección y realización']],
    conditionTitle: 'Condición técnica profesional', conditionText: 'Trabajamos con equipos propios o con equipos del cliente solo cuando cumplen los requisitos mínimos para garantizar estabilidad, calidad de imagen, audio y transmisión.',
    finalEyebrow: '¿Listo para tu evento?', finalTitle: 'Planifiquemos tu proyecto audiovisual', finalText: 'Cuéntanos qué quieres producir y te ayudaremos a definir el sistema técnico, equipo humano, montaje y flujo de trabajo ideal.',
  },
  en: {
    cta: 'Plan my event', heroEyebrow: 'Audiovisual solutions', heroTitle: 'Events, streaming and live production', heroText: 'We plan, configure and operate audiovisual systems for in-person events, multicamera streams, podcasts and teams that need professional production quality.', heroSecondary: 'View capabilities',
    trust: [['Professional production', 'From pre-production to final delivery'], ['In-person events', 'Barcelona and projects across Spain'], ['Stable broadcasting', 'Full HD as standard and 4K on request'], ['Technical setup', 'Cameras, audio, lights, switcher and intercom']],
    servicesEyebrow: 'Our services', servicesTitle: 'Complete audiovisual solutions', servicesText: 'We focus mainly on events and professional streaming, with additional capabilities for podcasts, installations, post-production and technical training.',
    services: [['Professional streaming', 'We broadcast multicamera events to YouTube, Facebook, TikTok, Instagram, Zoom, Teams or your own website, with graphics, console audio and simultaneous recording.'], ['TV direction and live shows', 'We design the pre-production, technical script, rundown, camera shots, operator coordination and live direction from switcher and intercom.'], ['Podcast production', 'We create video podcast setups with cameras, separated audio channels, lighting, graphics, intro/outro and clips for social media.'], ['Audiovisual installation', 'Temporary or fixed installations for rooms, companies, schools, churches and venues that need cameras, sound, lighting or streaming.'], ['Video post-production', 'Basic, intermediate or advanced editing, multicamera edits, reels, subtitles, audio cleanup, basic color and graphics.'], ['Technical training', 'We train internal teams to operate cameras, audio, lighting, streaming and basic production workflows.']],
    streamingEyebrow: 'Featured service', streamingTitle: 'We broadcast your event wherever your audience is', streamingText: 'We build stable, professional and well-planned streams for in-person events, conferences, brands, churches, agencies and creators.', streamingCta: 'Plan my stream',
    streamingBullets: ['Multiplatform: YouTube, Facebook, TikTok, Instagram and own website', 'Zoom, Teams and closed events', 'Multicamera production with graphics and lower thirds', 'Professional audio from console', 'Simultaneous clean and graphic recording', 'AI subtitles on request', 'Full HD 1080p as standard and 4K by quote'],
    trainingEyebrow: 'Technical training', trainingTitle: 'We train your team to produce with confidence', trainingText: 'We train company, school, university, church and institution teams so they can operate their own audiovisual systems with more confidence.',
    trainingBullets: ['DSLR, mirrorless, studio, PTZ cameras and configuration', 'Professional audio and digital consoles', 'Lighting, DMX, Avolites or GrandMA depending on the project', 'Streaming and live direction', 'Workflows before, during and after the event', '1 to 3 day training depending on the need'],
    toolsEyebrow: 'Technology and software', toolsTitle: 'Tools we master', toolsText: 'We work with professional tools to produce, broadcast, record, edit and deliver high-quality audiovisual content.', equipmentTitle: 'Professional equipment',
    processEyebrow: 'Our process', processTitle: 'How we work on your project',
    process: [['Analysis and meeting', 'We understand the event, goals, duration, format and technical requirements.'], ['Design and proposal', 'We create the technical proposal, equipment plan, roles, technical script and production plan.'], ['Setup and testing', 'We install cameras, audio, lights, network, switcher and run tests before going live.'], ['Live production', 'We operate and direct the event with communication, technical control and maximum stability.'], ['Final delivery', 'We deliver streaming, clean recording, graphic version or edited material.']],
    projectsEyebrow: 'Selected work', projectsTitle: 'Spaces for your real photos', projectsText: 'Here you can upload real images of events, streaming, podcasts, installations and technical backstage from Directus.',
    projects: [['Corporate event', 'Multicamera broadcast'], ['Conference', 'Streaming and technical operation'], ['Professional podcast', 'Set, cameras, audio and lighting'], ['Audiovisual installation', 'System ready to operate'], ['Live show', 'Direction and realization']],
    conditionTitle: 'Professional technical condition', conditionText: 'We work with our own equipment or client equipment only when it meets the minimum requirements to guarantee stability, image quality, audio and broadcasting.',
    finalEyebrow: 'Ready for your event?', finalTitle: 'Let’s plan your audiovisual project', finalText: 'Tell us what you want to produce and we will help you define the right technical system, crew, setup and workflow.',
  },
} as const;

const tools = ['OBS', 'vMix', 'MimoLive', 'ATEM Software Control', 'Blackmagic Design', 'DaVinci Resolve', 'Premiere Pro', 'Final Cut', 'After Effects', 'Audition', 'Logic Pro', 'FL Studio', 'Photoshop', 'Canva', 'CapCut'];
const equipment = { es: ['Cámaras DSLR / mirrorless', 'Cámaras de estudio con CCU', 'Cámaras PTZ', 'Switcher ATEM', 'Consolas Yamaha / DiGiCo', 'Micrófonos inalámbricos UHF', 'Intercom', 'Luces LED', 'Pantallas LED', 'Proyectores', 'Capturadoras HDMI / SDI', 'Mezcladores de video'], en: ['DSLR / mirrorless cameras', 'Studio cameras with CCU', 'PTZ cameras', 'ATEM switcher', 'Yamaha / DiGiCo consoles', 'Wireless UHF microphones', 'Intercom', 'LED lights', 'LED screens', 'Projectors', 'HDMI / SDI capture cards', 'Video mixers'] };
const serviceIcons = [Radio, Tv, Mic2, Settings2, Clapperboard, GraduationCap];
const trustIcons = [BadgeCheck, Camera, MonitorPlay, Settings2];
const processIcons = [Sparkles, WandSparkles, Settings2, Radio, Check];
const projectIcons = [Video, MonitorPlay, Mic2, Camera, Tv];

function ImageSlot({ item, attr, title, text, className = '', dark = false }: { item?: PageElement; attr?: string; title: string; text: string; className?: string; dark?: boolean }) {
  if (item?.image_url) return <div data-directus={attr} className={`relative overflow-hidden rounded-[1.4rem] ${className}`}><img src={item.image_url} alt={title} className="h-full w-full object-cover" /></div>;
  return <div data-directus={attr} className={`flex min-h-[260px] items-center justify-center rounded-[1.4rem] border-2 border-dashed p-6 text-center ${dark ? 'border-white/25 bg-white/[.04] text-white' : 'border-[#D4AF37]/35 bg-[#F7F3EA] text-[#061523]'} ${className}`}><div><Camera className="mx-auto text-[#D4AF37]" size={38} /><h3 className="mt-4 text-xl font-black">{title}</h3><p className={`mx-auto mt-3 max-w-sm text-sm leading-6 ${dark ? 'text-white/65' : 'text-[#061523]/60'}`}>{text}</p></div></div>;
}

export default function AudiovisualSolutionsPageClient({ pageElements = [] }: { pageElements?: PageElement[] }) {
  const [locale, setLocale] = useState<Locale>('es');
  const [visualEditingEnabled, setVisualEditingEnabled] = useState(false);

  useEffect(() => { const stored = window.localStorage.getItem(LOCALE_KEY); if (stored === 'en' || stored === 'es') setLocale(stored); setVisualEditingEnabled(isDirectusVisualEditingFrame()); }, []);
  const handleLocale = (value: Locale) => { setLocale(value); window.localStorage.setItem(LOCALE_KEY, value); };
  const page = 'service-audiovisual';
  const base = copy[locale];
  const item = (key: string) => pageElement(pageElements, page, locale, key);
  const globalItem = (key: string) => pageElement(pageElements, 'global', locale, key);
  const value = (key: string, fallback: string, field: Field = 'text') => field === 'image' ? fallback : elementText(item(key), fallback, field);
  const attr = (key: string, field: Field = 'text') => directusAttr(visualEditingEnabled, 'page_elements', item(key)?.id, field);
  const keys = ['home', 'services', 'portfolio', 'process', 'contact'];
  const links = navLinks[locale].map(([label, href], index) => { const nav = globalItem(`nav.${keys[index]}`); return [elementText(nav, label), nav?.link || href] as NavLink; });

  const trustItems = base.trust.map(([title, text], i) => [value(`trust.${i + 1}`, title), value(`trust.${i + 1}`, text, 'secondary_text')] as const);
  const services = base.services.map(([title, text], i) => [value(`services.${i + 1}`, title), value(`services.${i + 1}`, text, 'secondary_text')] as const);
  const streamBullets = base.streamingBullets.map((text, i) => value(`streaming.bullet.${i + 1}`, text));
  const trainBullets = base.trainingBullets.map((text, i) => value(`training.bullet.${i + 1}`, text));
  const process = base.process.map(([title, text], i) => [value(`process.${i + 1}`, title), value(`process.${i + 1}`, text, 'secondary_text')] as const);
  const projects = base.projects.map(([title, text], i) => [value(`projects.${i + 1}`, title), value(`projects.${i + 1}`, text, 'secondary_text'), item(`projects.${i + 1}.image`)] as const);

  return <main className="min-h-screen overflow-hidden bg-[#F7F3EA] text-[#061523]">
    <DirectusVisualEditing enabled={visualEditingEnabled} refreshKey={`audiovisual:${locale}:${pageElements.length}`} />
    <Navbar links={links} ctaLabel={elementText(globalItem('nav.cta'), value('hero.cta', base.cta))} locale={locale} onLocaleChange={handleLocale} transparentOnTop editableLinks={keys.map(key => globalItem(`nav.${key}`))} ctaElement={globalItem('nav.cta')} visualEditingEnabled={visualEditingEnabled} pageElements={pageElements} />

    <section className="relative overflow-hidden bg-[#061523] px-5 pb-10 pt-28 text-white md:px-8 md:pt-32">
      {item('hero.image')?.image_url ? <img src={item('hero.image')?.image_url} alt="" className="absolute inset-0 h-full w-full object-cover opacity-70" data-directus={attr('hero.image', 'image')} /> : <div className="absolute inset-y-0 right-0 hidden w-[58%] md:block"><ImageSlot item={item('hero.image')} attr={attr('hero.image', 'image')} title="Hero image" text="Sube aquí una foto real de evento, cámaras o streaming." dark className="h-full rounded-none border-0 opacity-80" /></div>}
      <div className="absolute inset-0 bg-[linear-gradient(90deg,#061523_0%,rgba(6,21,35,.94)_35%,rgba(6,21,35,.58)_58%,rgba(6,21,35,.18)_100%)]" />
      <div className="absolute inset-0 opacity-25 [background-image:radial-gradient(circle_at_18%_20%,rgba(212,175,55,.22),transparent_25%),radial-gradient(circle_at_85%_5%,rgba(0,166,166,.24),transparent_30%)]" />
      <div className="relative mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_.9fr]">
        <div className="max-w-3xl py-16 md:py-24"><p className="text-xs font-black uppercase tracking-[.24em] text-[#D4AF37]" data-directus={attr('hero.eyebrow')}>{value('hero.eyebrow', base.heroEyebrow)}</p><h1 className="mt-5 text-5xl font-black leading-[.95] tracking-[-.055em] md:text-7xl" data-directus={attr('hero.title')}>{value('hero.title', base.heroTitle)}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/78" data-directus={attr('hero.text')}>{value('hero.text', base.heroText)}</p><div className="mt-9 flex flex-wrap gap-4"><a href="#contacto" className="inline-flex items-center gap-3 rounded-xl bg-[#D4AF37] px-6 py-4 font-black text-[#061523] transition hover:-translate-y-1 hover:bg-white" data-directus={attr('hero.cta')}>{value('hero.cta', base.cta)} <ArrowRight size={18} /></a><a href="#servicios" className="inline-flex items-center gap-3 rounded-xl border border-white/20 px-6 py-4 font-black text-white transition hover:border-[#D4AF37] hover:text-[#D4AF37]" data-directus={attr('hero.secondary')}>{value('hero.secondary', base.heroSecondary)}</a></div></div>
        <div className="relative hidden items-end lg:flex">{!item('hero.image')?.image_url && <div className="mb-16 w-full"><ImageSlot item={item('hero.image')} attr={attr('hero.image', 'image')} title="Foto principal" text="Espacio editable para subir una foto real de evento, streaming, cámara o backstage técnico." dark className="min-h-[440px]" /></div>}</div>
      </div>
      <div className="relative mx-auto grid max-w-7xl gap-4 border-t border-white/10 py-6 md:grid-cols-4">{trustItems.map(([title, text], i) => { const Icon = trustIcons[i]; return <div key={title} className="flex items-start gap-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full border border-[#D4AF37]/45 text-[#D4AF37]"><Icon size={20} /></span><div><h3 className="font-black" data-directus={attr(`trust.${i + 1}`)}>{title}</h3><p className="mt-1 text-sm leading-5 text-white/60" data-directus={attr(`trust.${i + 1}`, 'secondary_text')}>{text}</p></div></div>; })}</div>
    </section>

    <section id="servicios" className="bg-[#F7F3EA] px-5 py-20 md:px-8"><div className="mx-auto max-w-7xl text-center"><p className="text-xs font-black uppercase tracking-[.22em] text-[#B88A1A]" data-directus={attr('services.eyebrow')}>{value('services.eyebrow', base.servicesEyebrow)}</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em] md:text-6xl" data-directus={attr('services.title')}>{value('services.title', base.servicesTitle)}</h2><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-[#061523]/65" data-directus={attr('services.text')}>{value('services.text', base.servicesText)}</p></div><div className="mx-auto mt-12 grid max-w-7xl gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map(([title, text], i) => { const Icon = serviceIcons[i]; return <article key={title} className="group rounded-[1.5rem] border border-[#D4AF37]/18 bg-white p-7 shadow-[0_20px_60px_rgba(0,33,71,.08)] transition hover:-translate-y-1 hover:border-[#D4AF37]/55"><span className="flex h-16 w-16 items-center justify-center rounded-2xl bg-[#F7F3EA] text-[#B88A1A] ring-1 ring-[#D4AF37]/25"><Icon size={30} /></span><h3 className="mt-6 text-2xl font-black tracking-[-.03em]" data-directus={attr(`services.${i + 1}`)}>{title}</h3><p className="mt-4 text-base leading-7 text-[#061523]/64" data-directus={attr(`services.${i + 1}`, 'secondary_text')}>{text}</p><span className="mt-6 inline-flex text-[#B88A1A]"><ArrowRight size={20} /></span></article>; })}</div></section>

    <section className="relative overflow-hidden bg-[#061523] px-5 py-20 text-white md:px-8"><div className="absolute inset-0 bg-[radial-gradient(circle_at_15%_15%,rgba(212,175,55,.18),transparent_26%),radial-gradient(circle_at_78%_10%,rgba(0,166,166,.18),transparent_30%)]" /><div className="relative mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-[.85fr_1fr]"><div><p className="text-xs font-black uppercase tracking-[.22em] text-[#D4AF37]" data-directus={attr('streaming.eyebrow')}>{value('streaming.eyebrow', base.streamingEyebrow)}</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em] md:text-6xl" data-directus={attr('streaming.title')}>{value('streaming.title', base.streamingTitle)}</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-white/72" data-directus={attr('streaming.text')}>{value('streaming.text', base.streamingText)}</p><div className="mt-7 grid gap-3">{streamBullets.map((text, i) => <span key={text} className="flex items-start gap-3 text-base leading-6 text-white/82"><Check className="mt-0.5 shrink-0 text-[#D4AF37]" size={18} /><span data-directus={attr(`streaming.bullet.${i + 1}`)}>{text}</span></span>)}</div><a href="#contacto" className="mt-9 inline-flex items-center gap-3 rounded-xl bg-[#D4AF37] px-6 py-4 font-black text-[#061523] transition hover:-translate-y-1 hover:bg-white" data-directus={attr('streaming.cta')}>{value('streaming.cta', base.streamingCta)} <ArrowRight size={18} /></a></div><ImageSlot item={item('streaming.image')} attr={attr('streaming.image', 'image')} title={locale === 'es' ? 'Foto de streaming' : 'Streaming photo'} text={locale === 'es' ? 'Sube una foto real de realización multicámara, switcher, cámaras o evento.' : 'Upload a real photo of multicamera production, switcher, cameras or event.'} dark className="min-h-[420px]" /></div></section>

    <section className="bg-[#F7F3EA] px-5 py-20 md:px-8"><div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-[1fr_.9fr]"><ImageSlot item={item('training.image')} attr={attr('training.image', 'image')} title={locale === 'es' ? 'Foto de capacitación' : 'Training photo'} text={locale === 'es' ? 'Sube una foto real de capacitación, setup técnico, equipo interno o sala.' : 'Upload a real photo of training, technical setup, internal team or venue.'} className="min-h-[430px]" /><div><p className="text-xs font-black uppercase tracking-[.22em] text-[#B88A1A]" data-directus={attr('training.eyebrow')}>{value('training.eyebrow', base.trainingEyebrow)}</p><h2 className="mt-4 text-4xl font-black tracking-[-.04em] md:text-6xl" data-directus={attr('training.title')}>{value('training.title', base.trainingTitle)}</h2><p className="mt-5 text-lg leading-8 text-[#061523]/68" data-directus={attr('training.text')}>{value('training.text', base.trainingText)}</p><div className="mt-7 grid gap-3">{trainBullets.map((text, i) => <span key={text} className="flex items-start gap-3 text-base leading-6 text-[#061523]/82"><Check className="mt-0.5 shrink-0 text-[#B88A1A]" size={18} /><span data-directus={attr(`training.bullet.${i + 1}`)}>{text}</span></span>)}</div></div></div></section>

    <section className="bg-[#061523] px-5 py-18 text-white md:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2"><div><p className="text-xs font-black uppercase tracking-[.22em] text-[#D4AF37]" data-directus={attr('tools.eyebrow')}>{value('tools.eyebrow', base.toolsEyebrow)}</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em]" data-directus={attr('tools.title')}>{value('tools.title', base.toolsTitle)}</h2><p className="mt-4 max-w-xl text-base leading-7 text-white/65" data-directus={attr('tools.text')}>{value('tools.text', base.toolsText)}</p><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3">{tools.map((tool, i) => <span key={tool} className="rounded-xl border border-white/12 bg-white/[.05] px-4 py-3 text-sm font-black" data-directus={attr(`tools.${i + 1}`)}>{value(`tools.${i + 1}`, tool)}</span>)}</div></div><div><h2 className="text-4xl font-black tracking-[-.04em]" data-directus={attr('equipment.title')}>{value('equipment.title', base.equipmentTitle)}</h2><div className="mt-8 grid grid-cols-2 gap-3">{equipment[locale].map((eq, i) => <span key={eq} className="flex items-center gap-3 rounded-xl border border-white/12 bg-white/[.05] px-4 py-3 text-sm font-bold text-white/82"><Settings2 className="shrink-0 text-[#D4AF37]" size={17} /><span data-directus={attr(`equipment.${i + 1}`)}>{value(`equipment.${i + 1}`, eq)}</span></span>)}</div></div></div></section>

    <section className="bg-[#F7F3EA] px-5 py-20 md:px-8"><div className="mx-auto max-w-7xl text-center"><p className="text-xs font-black uppercase tracking-[.22em] text-[#B88A1A]" data-directus={attr('process.eyebrow')}>{value('process.eyebrow', base.processEyebrow)}</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em] md:text-6xl" data-directus={attr('process.title')}>{value('process.title', base.processTitle)}</h2></div><div className="mx-auto mt-12 grid max-w-7xl gap-5 md:grid-cols-5">{process.map(([title, text], i) => { const Icon = processIcons[i]; return <article key={title} className="relative rounded-[1.4rem] border border-[#D4AF37]/20 bg-white p-6 text-center shadow-[0_20px_50px_rgba(0,33,71,.06)]"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-[#D4AF37] text-[#061523]"><Icon size={24} /></span><p className="mt-5 text-sm font-black text-[#B88A1A]">{String(i + 1).padStart(2, '0')}</p><h3 className="mt-2 text-lg font-black" data-directus={attr(`process.${i + 1}`)}>{title}</h3><p className="mt-3 text-sm leading-6 text-[#061523]/62" data-directus={attr(`process.${i + 1}`, 'secondary_text')}>{text}</p></article>; })}</div></section>

    <section className="bg-[#061523] px-5 py-20 text-white md:px-8"><div className="mx-auto max-w-7xl"><div className="text-center"><p className="text-xs font-black uppercase tracking-[.22em] text-[#D4AF37]" data-directus={attr('projects.eyebrow')}>{value('projects.eyebrow', base.projectsEyebrow)}</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em] md:text-6xl" data-directus={attr('projects.title')}>{value('projects.title', base.projectsTitle)}</h2><p className="mx-auto mt-4 max-w-2xl text-lg leading-8 text-white/65" data-directus={attr('projects.text')}>{value('projects.text', base.projectsText)}</p></div>{visualEditingEnabled && <div className="my-8 rounded-2xl border border-[#D4AF37]/45 bg-[#061523] p-5"><p className="text-xs font-black uppercase tracking-[.22em] text-[#D4AF37]">Image fields</p><div className="mt-4 grid gap-3 md:grid-cols-4">{['hero.image','streaming.image','training.image','projects.1.image','projects.2.image','projects.3.image','projects.4.image','projects.5.image'].map(k => <button key={k} type="button" data-directus={attr(k, 'image')} className="rounded-xl border border-white/15 bg-white/[.06] px-4 py-3 text-left text-sm font-black text-white">{k}</button>)}</div></div>}<div className="mt-12 grid gap-5 md:grid-cols-5">{projects.map(([title, text, img], i) => { const Icon = projectIcons[i]; return <article key={title} className="overflow-hidden rounded-[1.4rem] border border-white/12 bg-white/[.05]"><ImageSlot item={img} attr={attr(`projects.${i + 1}.image`, 'image')} title={locale === 'es' ? 'Foto del proyecto' : 'Project photo'} text={locale === 'es' ? 'Sube una foto real aquí.' : 'Upload a real photo here.'} dark className="min-h-[180px] rounded-none border-0" /><div className="p-4"><Icon className="text-[#D4AF37]" size={22} /><h3 className="mt-3 font-black" data-directus={attr(`projects.${i + 1}`)}>{title}</h3><p className="mt-2 text-sm leading-5 text-white/58" data-directus={attr(`projects.${i + 1}`, 'secondary_text')}>{text}</p></div></article>; })}</div><div className="mt-12 rounded-[1.6rem] border border-[#D4AF37]/30 bg-white/[.05] p-7 text-center"><h3 className="text-2xl font-black" data-directus={attr('condition.title')}>{value('condition.title', base.conditionTitle)}</h3><p className="mx-auto mt-4 max-w-3xl text-base leading-7 text-white/70" data-directus={attr('condition.text')}>{value('condition.text', base.conditionText)}</p></div></div></section>

    <section className="bg-[#F7F3EA] px-5 py-20 md:px-8"><div className="mx-auto grid max-w-7xl gap-8 rounded-[2rem] border border-[#D4AF37]/22 bg-white p-8 shadow-[0_22px_70px_rgba(0,33,71,.08)] lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-xs font-black uppercase tracking-[.22em] text-[#B88A1A]" data-directus={attr('final.eyebrow')}>{value('final.eyebrow', base.finalEyebrow)}</p><h2 className="mt-3 text-4xl font-black tracking-[-.04em]" data-directus={attr('final.title')}>{value('final.title', base.finalTitle)}</h2><p className="mt-5 text-lg leading-8 text-[#061523]/65" data-directus={attr('final.text')}>{value('final.text', base.finalText)}</p></div><ContactSection locale={locale} source="d-solution.org/tecnologia-audiovisual" visualEditingEnabled={visualEditingEnabled} pageElements={pageElements} /></div></section>

    <SiteFooter locale={locale} pageElements={pageElements} visualEditingEnabled={visualEditingEnabled} />
  </main>;
}
