'use client';

import { useEffect, useState } from 'react';
import { ArrowRight, Bot, Camera, Code2, Megaphone, Palette, Radio } from 'lucide-react';
import Navbar, { type NavLink } from '@/components/Navbar';
import ContactSection from '@/components/ContactSection';
import SiteFooter from '@/components/SiteFooter';
import { SERVICE_LINKS } from '@/lib/services';

type Locale = 'es' | 'en';
const LOCALE_KEY = 'dsolution-language';
const icons = [Radio, Megaphone, Code2, Bot, Palette, Camera];
const copy = {
  es: { cta: 'Hablemos de tu proyecto', eyebrow: 'Soluciones digitales a medida', title: 'Encuentra la mejor solución digital para tu empresa', intro: 'Combinamos tecnología audiovisual, estrategia, diseño y automatización para ayudarte a comunicar mejor, organizar procesos y crecer con una ejecución clara.', noteTitle: 'Un enfoque conectado', note: 'No trabajamos con soluciones aisladas: elegimos la combinación de servicios que mejor se adapta a tus objetivos, recursos y momento de negocio.', cards: ['Producción, streaming, iluminación y soporte técnico para experiencias que se ven y se escuchan bien.', 'Estrategia, Google Ads, medición y campañas enfocadas en oportunidades reales.', 'Sitios corporativos, landing pages y experiencias web rápidas, claras y optimizadas.', 'Flujos inteligentes, integraciones y agentes que reducen tareas repetitivas.', 'Identidad visual y piezas creativas que hacen que tu marca sea reconocible y coherente.', 'Fotografía de producto, marca, retrato y eventos para comunicar con una imagen profesional.'], learn: 'Explorar servicio', flow: ['Entendemos el reto', 'Proponemos una solución', 'Ejecutamos con claridad'] },
  en: { cta: 'Let’s talk about your project', eyebrow: 'Tailored digital solutions', title: 'Find the best digital solution for your business', intro: 'We combine audiovisual technology, strategy, design and automation to help you communicate clearly, organise processes and grow with professional execution.', noteTitle: 'A connected approach', note: 'We do not work with isolated solutions: we choose the combination of services that best fits your goals, resources and current business stage.', cards: ['Production, streaming, lighting and technical support for experiences that look and sound right.', 'Strategy, Google Ads, measurement and campaigns focused on real opportunities.', 'Corporate sites, landing pages and fast, clear, optimised web experiences.', 'Intelligent workflows, integrations and agents that reduce repetitive tasks.', 'Visual identity and creative assets that keep your brand recognisable and coherent.', 'Product, brand, portrait and event photography for a professional visual presence.'], learn: 'Explore service', flow: ['We understand the challenge', 'We propose a solution', 'We execute with clarity'] },
} as const;

export default function ServicesOverviewClient() {
  const [locale, setLocale] = useState<Locale>('es');
  useEffect(() => { const saved = localStorage.getItem(LOCALE_KEY); if (saved === 'en' || saved === 'es') setLocale(saved); }, []);
  const switchLocale = (next: Locale) => { setLocale(next); localStorage.setItem(LOCALE_KEY, next); document.documentElement.lang = next === 'en' ? 'en' : 'es-ES'; };
  const t = copy[locale];
  const nav = (locale === 'es' ? [['Inicio', '/'], ['Servicios', '/servicios'], ['Portafolio', '/#portafolio'], ['Nosotros', '/#nosotros'], ['Blog', '/#blog'], ['Contacto', '#contacto']] : [['Home', '/'], ['Services', '/servicios'], ['Portfolio', '/#portafolio'], ['About', '/#nosotros'], ['Blog', '/#blog'], ['Contact', '#contacto']]) as NavLink[];
  return <main className="min-h-screen overflow-hidden bg-[#F8F9FA] text-[#002147]" style={{ backgroundImage: 'radial-gradient(circle at 6% 10%,rgba(212,175,55,.17),transparent 23%),radial-gradient(circle at 93% 20%,rgba(0,166,166,.12),transparent 24%),linear-gradient(180deg,#F8F9FA,#F4EFE4 53%,#F8F9FA)' }}>
    <Navbar links={nav} ctaLabel={t.cta} locale={locale} onLocaleChange={switchLocale} />
    <section className="relative px-5 pb-16 pt-32 md:px-8 md:pb-20 md:pt-40"><div className="pointer-events-none absolute -right-20 top-36 h-72 w-72 rounded-full border-[42px] border-[#D4AF37]/10"/><div className="pointer-events-none absolute -left-16 bottom-[-5rem] h-60 w-60 rounded-full border-[38px] border-[#00A6A6]/10"/>
      <div className="relative mx-auto max-w-6xl"><div className="grid gap-8 rounded-[2.2rem] border border-white/80 bg-white/80 p-8 shadow-[0_28px_75px_rgba(0,33,71,.12)] backdrop-blur-xl md:grid-cols-[1.1fr_.9fr] md:p-12"><div><p className="text-xs font-bold uppercase tracking-[.28em] text-[#B58F18]">{t.eyebrow}</p><h1 className="mt-4 max-w-3xl text-4xl font-semibold leading-tight tracking-tight md:text-6xl">{t.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#212529]/75">{t.intro}</p><div className="mt-9 flex flex-wrap gap-3">{t.flow.map((item, index) => <span key={item} className="inline-flex items-center gap-2 rounded-full border border-[#002147]/10 bg-[#F8F9FA] px-4 py-2 text-sm font-semibold text-[#002147]/80"><b className="text-[#D4AF37]">0{index + 1}</b>{item}</span>)}</div></div><div className="relative overflow-hidden rounded-[1.8rem] bg-[#002147] p-7 text-white"><div className="absolute -right-12 -top-12 h-36 w-36 rounded-full bg-[#D4AF37]/25 blur-2xl"/><div className="absolute -bottom-14 -left-14 h-44 w-44 rounded-full bg-[#00A6A6]/18 blur-2xl"/><div className="relative"><p className="text-xs font-bold uppercase tracking-[.25em] text-[#D4AF37]">D-Solution</p><h2 className="mt-4 text-2xl font-semibold">{t.noteTitle}</h2><p className="mt-4 leading-7 text-white/78">{t.note}</p><div className="mt-8 grid grid-cols-3 gap-3">{['01', '02', '03'].map((n, i) => <div key={n} className="rounded-2xl border border-white/10 bg-white/[.07] p-4"><div className="text-lg font-semibold text-[#D4AF37]">{n}</div><div className="mt-3 h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full bg-[#00A6A6]" style={{ width: `${55 + i * 18}%` }}/></div></div>)}</div></div></div></div></div>
    </section>
    <section className="px-5 pb-14 md:px-8"><div className="mx-auto grid max-w-6xl gap-5 md:grid-cols-2 lg:grid-cols-3">{SERVICE_LINKS.map((service, index) => { const Icon = icons[index]; return <a key={service.key} href={service.href} className="group relative overflow-hidden rounded-[1.8rem] border border-white bg-white p-7 shadow-[0_16px_45px_rgba(0,33,71,.09)] transition hover:-translate-y-2 hover:border-[#D4AF37]/60 hover:shadow-[0_24px_55px_rgba(0,33,71,.16)]"><div className="absolute -right-8 -top-8 h-28 w-28 rounded-full bg-[#D4AF37]/10 transition group-hover:scale-125"/><span className="relative inline-flex h-16 w-16 items-center justify-center rounded-2xl bg-[#002147] text-[#D4AF37]"><Icon size={29}/></span><h2 className="relative mt-7 text-2xl font-semibold">{locale === 'es' ? service.es : service.en}</h2><p className="relative mt-4 min-h-[84px] leading-7 text-[#212529]/75">{t.cards[index]}</p><span className="relative mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#002147] transition group-hover:text-[#D4AF37]">{t.learn}<ArrowRight size={16}/></span></a>; })}</div></section>
    <ContactSection locale={locale} source="d-solution.org/servicios" />
    <SiteFooter locale={locale} links={nav}/>
  </main>;
}
